#!/bin/zsh

# Copy pasted from
# https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu, edited to
# use wl-copy and stripping out the 'typeit' option.

password_files=( "$PASSWORD_STORE_DIR"/**/*.gpg )
password_files=( "${password_files[@]#"$PASSWORD_STORE_DIR"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | \
  wofi --prompt="Username search" --show dmenu "$@")

[[ -n $password ]] || exit

basename "$password" | wl-copy

notify-send 'Username Copied' "$password" -t 3000
