#!/bin/zsh

# Copy pasted from
# https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu, edited to
# use wl-copy and stripping out the 'typeit' option.

prefix=${PASSWORD_STORE_DIR-$XDG_DATA_HOME/pass}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | \
  wofi --prompt="One Time Password" --show dmenu "$@")

[[ -n $password ]] || exit

pass otp "$password" | wl-copy --trim-newline
