#!/bin/bash

# This is a small script for keeping an up-to-date todolist open

todo_dir=$XDG_DATA_HOME/calendars
tmp_file=/tmp/taskmon_refresh

monitor() {
  inotifywait             \
    --monitor             \
    --quiet               \
    --recursive           \
    --event move          \
    --event create        \
    --event delete        \
    $todo_dir
}

rm_temp() {
  sleep ${1:-1}
  [ -f $tmp_file ] && rm $tmp_file
}

# temp file is required for debouncing. Inotify prints several lines for each
# change.
update_list() {
  [ -f $tmp_file ] && return
  touch $tmp_file
  clear
  todo list --priority low --startable --no-reverse
  rm_temp &
}

# In case we didn't shut down cleanly
rm_temp 0

# First paint
update_list

# Update whenever inotify prints output
monitor | while read line; do
  update_list &
done
