#!/bin/bash

# Fuzzy-search a list of TLDR pages, starting with an optional query.

# If any arguments are passed, build parameter to pass to fzf:
if [ $# -gt 0 ]; then
  fzf_args="-q $* "
fi

# tldr --list returns a comma separated list; fzf wants them on lines.
tldr --list                                                       \
  | fzf $fzf_args --preview "echo {} | xargs tldr --color always" \
  | xargs -r tldr
