#!/bin/bash

# Copy pasted from
# https://git.zx2c4.com/password-store/tree/contrib/dmenu/passmenu, edited to
# use wl-copy and stripping out the 'typeit' option.

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

pass show "$password"      \
  | head -1                \
  | wl-copy --trim-newline \
  && sleep 1m              \
  ; wl-copy --clear
